CREATE TABLE DEPARTMENT
	(DEPARTMENT_CODE NUMBER(6),
	 DEPARTMENT_NAME VARCHAR2(100),
     DEPARTMENT_LOCATION VARCHAR2(200),
	 CONSTRAINT DEPARTMENT_CODE_ID PRIMARY KEY (DEPARTMENT_CODE));

CREATE TABLE REPRESENTATIVES
	(REP_CODE NUMBER(6)
	 CONSTRAINT REP_CODE_ID PRIMARY KEY,
	 REP_LNAME VARCHAR2(50),
	 CONSTRAINT REP_CODE_ID_FK
	 FOREIGN KEY (DEPARTMENT_CODE_ID)
	 REFERENCES DEPARTMENT (DEPARTMENT_CODE));

CREATE TABLE CUSTOMER
	(CUST_CODE NUMBER(6),
	 CUST_NAME VARCHAR2(50),
	 CUST_ADDRESS VARCHAR2(100),
	 CONSTRAINT CUST_CODE_ID PRIMARY KEY (CUST_CODE));

CREATE TABLE INVOICE
	(INV_NUMBER NUMBER(6),
     INV_AMT NUMBER(10),
	 REP_CODE NUMBER(6) CONSTRAINT REP_CODE_ID REFERENCES REPRESENTATIVES(REP_CODE),
	 CUST_CODE NUMBER(6) CONSTRAINT CUST_CODE_ID REFERENCES CUSTOMER(CUST_CODE),
	 CONSTRAINT ENROLLMENT REP_CODE CUST_CODE PRIMARY KEY (REP_CODE, CUST_CODE));
	 

	 